# 1 = 1s, 150 = 2.5 min, etc
$sysbar = ashell

listener {
    timeout = 600
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r; $sysbar
}

listener {
    timeout = 1200
    on-timeout = hyprlock
    on-resume = $sysbar
}

listener {
    timeout = 1800
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on; brightnessctl -r; $sysbar
}

listener {
    timeout = 2700
    on-timeout = systemctl suspend
    on-resume = $sysbar
}

