
# basic colors for the things
$main_color = rgba(9,177,138,1.0)

$background_color = rgba(35,31,35,1.0)
$gray_color = rgba(64,67,71,1.0)

$brighter_color = rgba(65,240,199,1.0)
$darker_color = rgba(11,106,85,1.0)
